### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by jcbatalha** [joncage/ed-scout#100]
Hi there,

I'd like to ask if there is any plan on making this tool available under Linux. I'd be interested in participating.
I'm already running EDMarketConnector under Linux, so I'd be most interested in getting EDScout also running under Linux. Btw, I believe headless mode would be enough.
Thanks

**Comment by joncage** [comment]
Its open source and python based so every chance we could get it running under Linux with a bit of effort. I don't have a Linux machine with ED on it right now so could be tricky to test initially...

**Comment by jcbatalha** [comment]
Very well. I guess I'll give it a try.
I've never done any serious programming in python, but I'm willing to try "porting" this tool to Linux.
I'll let you know of any progress.
Best regards

**Comment by joncage** [comment]
Happy to accept pull requests & offer advice / answer questions along the way 👌🏻

**Comment by joncage** [comment]
First step (so I could give this a try); How do you run Elite under Linux and what distro are you on?

**Comment by joncage** [comment]
Try checking out the code and running the commands in https://github.com/joncage/ed-scout/blob/master/Installer/PackageIt.bat 

I'll see what I can do on my end.

**Comment by jcbatalha** [comment]
Hi Jon,

I'd already sent you a few messages on FB, but then, decided to reach you here, and it worked ;)
I'm running Manjaro Linux, and Steam runs great. There's a compatibility layer called Proton that, in conjunction with Wine, allows to play windows games under Linux.

About the path: In windows it's probably hardcoded, if you have default configurations. But in Steam, if you don't stick to default settings, you can define game libraries, each on different paths. It would be nice to be able tell the app where the game is installed.

About the app, I understand it requires Chrome, but EDMarketConnector doesn't...

**Comment by jcbatalha** [comment]
I've already cloned the project, but haven't looked at the code, yet.
I'll have a look at it, later today ;)

**Comment by joncage** [comment]
Sounds good.

The chrome requirement is from `PyFlaskWebGui` which is what I used to turn it into a desktop app so if you want to run headless only you can then fire up whichever browser you like. My intention was just to make a desktop app for Windows (which is what I primarily use) and this was the path of least resistance ;-)

Yeah, I'm sure there's more we can do to make the paths less windows-centric. Could probably break that aspect out into a new module and have it handle windows vs linux pathing nice and tidily.

**Comment by jcbatalha** [comment]
Hey Jon,

Is there any particular version of python I should use?
Ran:
cd EDScoutWebUI
pyenv install 3.7.8

My pyenv command doesn't have a <run> instruction so I tried

pipenv run ./EDScout.py -no_app

and got this:

`pipenv run ./EDScout.py -no_app
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pipenv/core.py", line 1635, in system_which
    assert c.return_code == 0
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/pipenv", line 33, in <module>
    sys.exit(load_entry_point('pipenv==2020.8.13', 'console_scripts', 'pipenv')())
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pipenv/cli/command.py", line 448, in run
    do_run(
  File "/usr/lib/python3.8/site-packages/pipenv/core.py", line 2547, in do_run
    run_fn(*run_args, **run_kwargs)
  File "/usr/lib/python3.8/site-packages/pipenv/core.py", line 2474, in do_run_posix
    command_path = system_which(script.command)
  File "/usr/lib/python3.8/site-packages/pipenv/core.py", line 1637, in system_which
    result = fallback_which(command, allow_global=True)
  File "/usr/lib/python3.8/site-packages/pipenv/core.py", line 1583, in fallback_which
    result = find_python(finder, command)
  File "/usr/lib/python3.8/site-packages/pipenv/utils.py", line 2196, in find_python
    result = finder.find_python_version(line)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 262, in find_python_version
    version_dict = self.parse_major(major, minor=minor, patch=patch, arch=arch)
  File "/usr/lib/python3.8/site-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 209, in parse_major
    int(version_dict["major"]) if version_dict.get("major") is not None else major
ValueError: invalid literal for int() with base 10: './EDScout.py'
`

**Comment by joncage** [comment]
Yes, sorry you're right that it should be pioenv not pyenv!

```
cd EDScoutWebUI
pyenv install
pyenv run EDScout.py -no_app
```
It was tested with python 3.7 and that first install command is important so that python 3.7 (and all the other packages in the pioenv file are collected. I'll double check those commands when I'm back at my machine later. Not had a chance to double check them myself.since writing them..

**Comment by jcbatalha** [comment]
Here's how it went:
<pre>pipenv check
<b>Creating a virtualenv for this project…</b>
Pipfile: <font color="#AA0000"><b>/home/jcb/Documents/Elite/ed-scout/Pipfile</b></font>
<b>Using</b> <font color="#AA0000"><b>/home/jcb/.pyenv/versions/3.7.0/bin/python3.7m</b></font> <font color="#00AA00">(3.7.0)</font> <b>to create virtualenv…</b>
⠸ Creating virtual environment...<font color="#0000AA">created virtual environment CPython3.7.0.final.0-64 in 187ms</font>
<font color="#0000AA">  creator CPython3Posix(dest=/home/jcb/.local/share/virtualenvs/ed-scout-9DnsEjDY, clear=False, global=False)</font>
<font color="#0000AA">  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/jcb/.local/share/virtualenv/seed-app-data/v1.0.1)</font>
<font color="#0000AA">  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator</font>

<font color="#00AA00">✔ Successfully created virtual environment!</font> 
Virtualenv location: <font color="#00AA00">/home/jcb/.local/share/virtualenvs/ed-scout-9DnsEjDY</font>
<b>Checking PEP 508 requirements…</b>
<font color="#00AA00">Passed!</font>
<b>Checking installed package safety…</b>
<font color="#00AA00">All good!</font>
<font color="#00AA00"><b>[jcb@nightcrawler</b></font><font color="#AAAAAA"><b> ed-scout</b></font><font color="#00AA00"><b>]$</b></font> pipenv run python -m EDScoutWebUI.EDScout -no_app
Traceback (most recent call last):
  File &quot;/home/jcb/.pyenv/versions/3.7.0/lib/python3.7/runpy.py&quot;, line 193, in _run_module_as_main
    &quot;__main__&quot;, mod_spec)
  File &quot;/home/jcb/.pyenv/versions/3.7.0/lib/python3.7/runpy.py&quot;, line 85, in _run_code
    exec(code, run_globals)
  File &quot;/home/jcb/Documents/Elite/ed-scout/EDScoutWebUI/EDScout.py&quot;, line 7, in &lt;module&gt;
    import psutil
ModuleNotFoundError: No module named &apos;psutil&apos;
</pre>

**Comment by jcbatalha** [comment]
This was due do error in 'pipenv install':
<pre><b>nstalling dependencies from Pipfile.lock (418b62)…</b>
<font color="#AA5500">Ignoring atomicwrites: markers &apos;sys_platform == &quot;win32&quot;&apos; don&apos;t match your environment</font>
<font color="#AA5500">Ignoring colorama: markers &apos;sys_platform == &quot;win32&quot;&apos; don&apos;t match your environment</font>
<font color="#AA0000">An error occurred while installing</font> <font color="#00AA00">pywin32==228 --hash=sha256:a60d795c6590a5b6baeacd16c583d91cce8038f959bd80c53bd9a68f40130f2d --hash=sha256:11cb6610efc2f078c9e6d8f5d0f957620c333f4b23466931a247fb945ed35e89 --hash=sha256:37dc9935f6a383cc744315ae0c2882ba1768d9b06700a70f35dc1ce73cd4ba9c --hash=sha256:00eaf43dbd05ba6a9b0080c77e161e0b7a601f9a3f660727a952e40140537de7 --hash=sha256:ec16d44b49b5f34e99eb97cf270806fdc560dff6f84d281eb2fcb89a014a56a9 --hash=sha256:fa6ba028909cfc64ce9e24bcf22f588b14871980d9787f1e2002c99af8f1850c --hash=sha256:9b3466083f8271e1a5eb0329f4e0d61925d46b40b195a33413e0905dccb285e8 --hash=sha256:1f45db18af5d36195447b2cffacd182fe2d296849ba0aecdab24d3852fbf3f80 --hash=sha256:6e38c44097a834a4707c1b63efa9c2435f5a42afabff634a17f563bc478dfcc8 --hash=sha256:8319bafdcd90b7202c50d6014efdfe4fde9311b3ff15fd6f893a45c0868de203 --hash=sha256:af40887b6fc200eafe4d7742c48417529a8702dcc1a60bf89eee152d1d11209f --hash=sha256:ed74b72d8059a6606f64842e7917aeee99159ebd6b8d6261c518d002837be298</font>! Will try again.
  🐍   <font color="#00AA00"><b>▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉</b></font> 47/47 — <font color="#000000">00:00:11</font>
<b>Installing initially failed dependencies…</b>
[InstallError]:   File &quot;/usr/lib/python3.8/site-packages/pipenv/cli/command.py&quot;, line 232, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File &quot;/usr/lib/python3.8/site-packages/pipenv/core.py&quot;, line 2052, in do_install
[InstallError]:       do_init(
[InstallError]:   File &quot;/usr/lib/python3.8/site-packages/pipenv/core.py&quot;, line 1305, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File &quot;/usr/lib/python3.8/site-packages/pipenv/core.py&quot;, line 899, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File &quot;/usr/lib/python3.8/site-packages/pipenv/core.py&quot;, line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File &quot;/usr/lib/python3.8/site-packages/pipenv/core.py&quot;, line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ERROR: Could not find a version that satisfies the requirement pywin32==228 (from -r /tmp/pipenv-jdggc5yb-requirements/pipenv-qtftx53m-requirement.txt (line 1)) (from versions: none)
[pipenv.exceptions.InstallError]: ERROR: No matching distribution found for pywin32==228 (from -r /tmp/pipenv-jdggc5yb-requirements/pipenv-qtftx53m-requirement.txt (line 1))
<font color="#AA0000"><b>ERROR</b></font>: Couldn&apos;t install package: <font color="#AAAAAA"><b>pywin32</b></font>
 <font color="#AA5500">Package installation failed...</font>
  <b>☤  </b><font color="#00AA00"><b>▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉</b></font> 0/1 — <font color="#000000">00:00:00</font>
</pre>

**Comment by jcbatalha** [comment]
Of course, pywin32 isn't meant for Linux... I'd hoped it could be platform independent...

**Comment by joncage** [comment]
I think it still can be. Just needs a little work. I'll take another look and see what we can do - watch this space :-)

**Comment by joncage** [comment]
A quick check suggests it's just the window toggling code that needs pywin32

**Comment by jcbatalha** [comment]
;)
In the meanwhile, I'm trying to run it under wine.

**Comment by joncage** [comment]
Try this branch if you're able: https://github.com/joncage/ed-scout/tree/0100-LinuxSupport - I've tried to detect the platform and drop the win32 requirements (although window toggling won't work; I'll need to find some alternatives to do that on Linux but that can wait).

**Comment by mboquien** [comment]
Hello. Out of curiosity I tried this branch and it fails in EDScoutCore/SavedGamesLocator.py because of the import of winreg. That being said, after commenting the import and editing save_game_root so it points to my Steam install, it passes this step. Then it starts but it does not appear do to anything out of the box:

```
2020-10-09T00:48:41.078Z - EDScoutWebUI-EDScout - INFO - ED Scout Beta Starting
2020-10-09T00:48:41.078Z - EDScoutWebUI-EDScout - DEBUG - Current process: 66537
2020-10-09T00:48:41.098Z - EDScoutWebUI-EDScout - INFO - Disabling caching
2020-10-09T00:48:41.105Z - EDScoutWebUI-EDScout - INFO - No HUD overrides file detected (/home/mederic/AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\GraphicsConfigurationOverride.xml)
2020-10-09T00:48:41.106Z - EDScoutCore-FileSystemUpdatePrompter - DEBUG - File size check: 23862
```
Note that the path to GraphicsConfigurationOverride.xml incrorrect but the fix should be similar as fixing the path to Saved Games.

Now if I connect directly to localhost:5000 it does comes to life and seems to be at least partly working:

![image](https://user-images.githubusercontent.com/444815/95529375-1f10fb00-09b1-11eb-9bad-ca4776d8b6b5.png)

Some information seems to be missing compared to https://github.com/joncage/ed-scout/blob/0100-LinuxSupport/Images/UIExplained.png but I am uncertain whether this is another bug or a Linux-specific issue.

**Comment by joncage** [comment]
Well done indeed - looks like that's working to me. The extra info shows up when you use the FSS to scan for celestial bodies. As you scan, you should see more information appearing near the top.

Thanks for giving this a shot. Next step would be to work out how we can auto-detevt locations on Linux to is works out of the box 👌🏻

**Comment by jcbatalha** [comment]
Hi there,

I've managed to get this working also...
Like Médéric, had to change a few things:
* in file EDScoutWebUI/EDScout.py, commented lines 21 and 222;
* in file EDScoutCore/SavedGamesLocator.py,  changed variable save_game_root so it points to my Steam install folder

Here, an example of a route with three discovered and four undiscovered systems:
![image](https://user-images.githubusercontent.com/7897076/95641796-47c1ef00-0a9c-11eb-88cf-5a14b131081f.png)

Thank you so much for your time and effort.
Please let me know if you need any help. I'll be glad to.

**Comment by pascaldulieu** [comment]
I've just cloned the main repo and branch 0100 before it was merged and I'm getting the following error on run

```
Traceback (most recent call last):
  File "/home/pascal/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/pascal/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pascal/Repositories/ed-scout/EDScoutWebUI/EDScout.py", line 28, in <module>
    from EDScoutWebUI.VersionChecker import check_version
  File "/home/pascal/Repositories/ed-scout/EDScoutWebUI/VersionChecker.py", line 6, in <module>
    from EDScoutWebUI import version
ImportError: cannot import name 'version' from 'EDScoutWebUI' (/home/pascal/Repositories/ed-scout/EDScoutWebUI/__init__.py)
```

**Comment by BinaryEnigma01** [comment]
I had the same problem as @pascaldulieu , but I'm using the latest version (not release) on the main branch, after fiddling around and making a mock 'version' akin to what was already in `EDScout.py` as well as hardcoding my journal path in `SavedGamesLocator.py`, it seemingly started working, although the UI shows UNKNOWN star system and no data, possibly due to the bad requests listed in the produced [log](https://pastebin.com/B3ADesNz) - I'm guessing my version hack failed horribly

**Comment by MrTimbones** [comment]
I was able to get EDScout 1.7.1 to run natively on Linux after a few hacks:

1. comment out windows includes until those errors went away
2. create 'EDScoutWebUI/version.py' containing two lines: `release = "v1.7.1"` and `version = "v1.7.1"`
3. modify 'SavedGamesLocator.py' to point right place (Epic Games + Wine in my case)
4. update 'EDScoutWebUI/templates.html' to use newer version of socket.io.js (e.g. 3.1.1)
(otherwise you get "client is using an unsupported version of the Socket.IO" errors that @BinaryEnigma01 had)
