### ISSUE TITLE
Virus Warning from Norton 360

### ISSUE THREAD

**Issue by Madtul** [joncage/ed-scout#101]
Hi All,

I went to download the Edscout.exe file today and my Norton 360 reports a danger.
It is identifying Heur.AdvML.B a heuristic virus in the file.

Let's hope this is a false positive.

**Comment by joncage** [comment]
I'm confident it is. When I get a chance I'll report it to them and get it cleared here: https://submit.norton.com/

**Comment by Madtul** [comment]
Super - just said I would let you know in case it may have prevented people from using / downloading the tool.
D2EA did I nice video on the tool btw.

**Comment by joncage** [comment]
Reports like this are much appreciated. And yeah, I was quite shocked when a buddy of mine mentioned he'd picked it up ...and I was pleasantly surprised to see how impressed he seemed with it 👌🏻

**Comment by joncage** [comment]
Submitted: https://submit.norton.com/?type=CHECK&submission_id=46231646-a081-4871-bff6-7825db789ca0

**Comment by joncage** [comment]
Still waiting for Norton to take a look...

![image](https://user-images.githubusercontent.com/73681/94809690-e12d3900-03ea-11eb-94a3-e880bb043008.png)

**Comment by joncage** [comment]
Still waiting 🙄

**Comment by joncage** [comment]
Still says it's processing. Maybe Norton have furloughed their checking staff?

**Comment by joncage** [comment]
Looks like Norton are still not bothering to do anything about this so I'm closing this for now
