### ISSUE TITLE
Highlight landable planets with high gravity

### ISSUE THREAD

**Issue by marcofilipa** [joncage/ed-scout#117]
We've all been there. "Hey look, a cool planet with volcanism! I'm just gonna land there and check it out" and then boom... you just crash on the planet and lose your exploration data because you forgot to check the gravity on the planet and turns out, it's a 1.5G.

From what I saw in the journal files, the gravity data is present in the _SurfaceGravity_ field of _Scan_ type events so you shouldn't need to change the core of the app, only the web rendering. 
It would be great to have visual awareness of these bodies in the interface, without having to open the System Map. It could be another icon next to the landable sign, representing high G body; or even a small border around the body entry for instance.

Let me know what you think. I can open a PR with that change

**Comment by joncage** [comment]
I think that's an excellent idea. No need to open another one - the detail here is just fine for a request.

The question is, how much gravity is too much gravity i.e. where do we set the bar?

**Comment by joncage** [comment]
Just be gentle when you're hunting through the code. At web dev i am no master 😉

**Comment by Rhaedas** [comment]
I think anything past 1g should have some warning. 2 isn't bad, but the point is to have a warning beforehand so you don't assume anything, and going in quick on a 2 could get touchy. What about a diamond warning sign with "g" inside, over 1 g is yellow, over 2 orange, over 3 red. Adjust the numbers if need be, maybe even have it so users can adjust them in the ini (for experienced pilots who know their limits).

**Comment by joncage** [comment]
Configurable limits in the config file for warning (amber) and high-alert (red) both with a black background sound like a neat idea. Could display it after the body name or as another icon. Displaying the number of G to 1.d.p if it's over the 1g limit could work well I think. Could overlay the landable icon with it as another possible.option.

Need to prototype a few.of these and fly with them for. A bit to see (that's how I normally try out new ideas)..

**Comment by marcofilipa** [comment]
My initial idea was to keep it simple and just display another icon if the gravity is >= 1.0G. 
 I'm not the most experienced explorer but I don't think I've encountered many landable planets above 2.0G. In any case, @Rhaedas I really like your idea of color progression depending on the value. Sounds good to me as well! 

@joncage let me know if you need help with the prototypes. Either of the variants we've been talking about sound like a simple feature to implement and I'm more than glad to contribute and put my hands on the code if needed

**Comment by joncage** [comment]
Happy to receive a pull request. I think I'm sold.on an extra signal that appears to the right of the landable icon. Just text that appears orange of 1.0-1.9G and red if 2.0+ by default.

Then add come config options to adjust those thresholds.

Keeping this info right next to the landable icon keeps the information together and makes it quicker to grok

**Comment by joncage** [comment]
Not a bad start:

![image](https://user-images.githubusercontent.com/73681/95259856-be9e8400-081f-11eb-8135-c76a54013f50.png)

Just need to:

1. Add some background clearing behind the numbes to the colour is always legible.
1. Adjust the styles when it's looking like a tricky landing (javascript is in there to add the tags, just need the CSS).

I'm wondering if the landable flag should be included in this black box so it's another clear indicator?

**Comment by joncage** [comment]
![image](https://user-images.githubusercontent.com/73681/95261010-8d26b800-0821-11eb-8874-ce8c4d9e0520.png)

Tada!

**Comment by marcofilipa** [comment]
Ahhh! You beat me to it, I was now cloning the repo. Heh.

That's it mate! Now is just a matter of styling it the way you feel appropriate for the app! Nice work!

**Comment by joncage** [comment]
Looks like the text in that span is shuffled down by two pixels annoyingly which means the black surround hits the bottom of the div that contains it. I'll push what I've got so far - see what you think in the `0117-AddHighGIndicator` branch I've just pushed.

**Comment by marcofilipa** [comment]
It's looking ok on my end:
![Capture](https://user-images.githubusercontent.com/1763482/95273962-6629af80-083c-11eb-87ff-bbbac2c11060.PNG)

**Comment by Rhaedas** [comment]
Like what you all are putting together, I think the numbers approach works well, gives more info than my first idea of a range symbol. 9.8 - ow, my back.

**Comment by joncage** [comment]
One more touch I've been mulling over today to add. I'm going to make it so landable planets always get a number next to them but it'll be green for low G planets.

I'll also expand the black background around the landable icon to tie them together.

If that pans out, it should make a nice neat consistent solution I think.

After a bit of flying around last night with the first attempt at this I've suddenly realised there are a lot of 6+G planets out there. I say am 8.4 too.. ...although they were all boring ice planets so not something I would have attempted a landing on.

**Comment by marcofilipa** [comment]
Awesome! I think this is going to help a lot of explorers out there! Thank you for the support!
