### ISSUE TITLE
Color customization

### ISSUE THREAD

**Issue by Rhaedas** [joncage/ed-scout#12]
Simplest thing to do without creating a settings menu would be to have the css between the <style> tags in the index.html be separate in its own .css file located where the .exe is. The user can tweak the numbers there without having to rebuild the file.

**Comment by joncage** [comment]
Sounds simple enough although it would be nice if it still came as a single .exe by default and you could specify the .CSS file via the command line to replace the internal one perhaps. Could make the application generate a template if the command line option doesn't exist yet (so that changes in the future can easily be accommodated by enthusiastic re-skinners?

**Comment by Rhaedas** [comment]
Lots of ways to take this. I like the idea of generating something for the user to change, perhaps put it in with the log file? Another level would be a menu on the main app to pull up either numbers or a sample of screen to adjust colors. A second choice would be an option to pull from the user's profile of the game to duplicate their HUD colors. That would need some translation of the matrix to proper RGB, but it's been done in a few apps already for the HUD change specifically. It's a cosmetic thing and not functional, but HUD colors is a big deal to a lot of people.

**Comment by joncage** [comment]
Pulling from the user's settings and doing the same colour transformation sounds like the right solution and a neat integration. Would probably work well colour wise too as I've replicated the in-game colours for the rest of the HUD. Just need to take a look at how the colours are applied...

**Comment by Rhaedas** [comment]
Also remember that there's a few different possible settings locations, so might have to prompt the first time for a path. I suppose you could have it look in the different areas to see if anything exists, but there's always a wildcard out there that's different from the norm.

**Comment by joncage** [comment]
Do you have a reference for that? I thought it was just one file?

**Comment by Rhaedas** [comment]
It's just a snippet out of a single file (the 3x3 matrix numbers for red, green, and blue) but depending on how the game was installed the file could be in a few places. Main difference is if it is run through Steam or not, but a few players could have also installed it on a different drive as well, and in older installations some of the paths varied for some reason. There's also the issue of if they're using the GraphicsConfiguration.xml or if they made a GraphicsConfigurationOverride.xml to keep updates from changing the values.

**Comment by joncage** [comment]
Gotcha. Maybe the simplest answer is to pick a sensible default directory and try for both file names. Then add a configuration option so you can specify it.

**Comment by Rhaedas** [comment]
Reasonable. See if it's under the Steam apps folder or user AppData, then ask if that's the correct one with option to edit/enter. Check for the Override file first, since it will have priority over the default.

**Comment by joncage** [comment]
Added code to load from `C:\Users\<user>\AppData\Local\Frontier Developments\Elite Dangerous\Options\Graphics\GraphicsConfigurationOverride.xml` for now - will add other paths as and when they're reported.
