### ISSUE TITLE
Gravity indicators aren't show in the web server

### ISSUE THREAD

**Issue by packet1** [joncage/ed-scout#129]
Gravity indicators aren't show in the web server

**Comment by joncage** [comment]
Do you have a screen shot of this? They only appear for landable planets.

**Comment by packet1** [comment]
![image](https://user-images.githubusercontent.com/70610088/95693897-77840a80-0bf4-11eb-8773-efcf05c6c413.png)

**Comment by packet1** [comment]
Disabled ADblock Plus and now it loads properly.  Go figure!

**Comment by joncage** [comment]
Weird! Well spotted though and thanks for reporting. That's good to know in case anyone else has that issue. Good work Cmdr! o7
