### ISSUE TITLE
Which Font Do I Need To Download

### ISSUE THREAD

**Issue by SurfinBird37** [joncage/ed-scout#140]
Hi, great program!  Which font do I need to download so that the program looks like the screenshots?

**Comment by joncage** [comment]
Eurostile is the one: https://www.cufonfonts.com/font/eurostile

**Comment by joncage** [comment]
There's some discussion on it here: https://www.reddit.com/r/EliteDangerous/comments/2o8883/for_the_typophiles_and_scifi_fans_guess_what_font/

**Comment by SurfinBird37** [comment]
Thank you so much!  Really loving the software btw, it's been very helpful, thanks!

**Comment by joncage** [comment]
Always good to hear 👌🏻
