### ISSUE TITLE
Gravity icon is missing on iPad Safari

### ISSUE THREAD

**Issue by packet1** [joncage/ed-scout#141]
I'm using the ED scout webserver with an iPad and Safari.  The gravity icon does not for landable planets.  (I do not have Adbolock enabled on this ipad)

**Comment by joncage** [comment]
What version of safari is that? I have an iPad I can take a look at. I'm surprised it doesn't as it's just a simple `span` element but maybe there's more to it in Safari. I'll take a look when I get a chance - cheers for reporting!

**Comment by packet1** [comment]
Ipad 8th gen, IOS 14

**Comment by packet1** [comment]
The problem exists with chrome on iOS 14.

**Comment by packet1** [comment]
I just realized, for unknown reasons, 1.5.3 was loaded an not 1.7.  I must have had a stray exe placed somewhere.

**Comment by joncage** [comment]
Oops! I do love it when a bug report closes itself without any work 👌🏻😉
