### ISSUE TITLE
Tooltips are not coming up

### ISSUE THREAD

**Issue by lunarplasma** [joncage/ed-scout#148]
I see that tooltips were added in #130 but in the current release v1.7.1, I don't see any when I hover over icons.

**Comment by lunarplasma** [comment]
It looks like the "title" attributes are not being added correctly.

**Comment by joncage** [comment]
Open to pull requests... 😉

**Comment by lunarplasma** [comment]
Oh, I think I see the issue. 1.7.1 was actually released before #130 was merged.

**Comment by joncage** [comment]
Ah yeah, there are a few bits that were going to go into the next release. I keep meaning to (and failing to kick off) an analysis of how much each type of body pays to improve the estimate accuracy...
