### ISSUE TITLE
Replace text with icons

### ISSUE THREAD

**Issue by joncage** [joncage/ed-scout#15]
For star type and planet type, it would look neater to add some icons instead of just plain text.

There are probably other aspects of the UI that would benefit from this too.

**Comment by Rhaedas** [comment]
Just a suggestion - you could create these icons from a screenshot of different bodies from various system maps. The caveat is that you may have to validate body types with the text, i.e. if you show a blue-white star, it probably should be one and not a red dwarf, just for consistency. Not sure how complicated that part might be.

**Comment by joncage** [comment]
What do you think @Rhaedas ?

![image](https://user-images.githubusercontent.com/73681/91300297-f6cf9300-e79a-11ea-9b04-9431ef43c841.png)

Still ironing out a few bits and pieces but it's coming together.

**Comment by Rhaedas** [comment]
Good start, can enhance it for future plans, or maybe it doesn't need to be too flashy, given the purpose of the program. I like the landable icon, that's useful too. Do you have more yet for different types of bodies in both the first and description columns (where the metal bar is)?

**Comment by joncage** [comment]
Yep. Icons for all the planet types (bad example there) - water worlds, earth like world's, icy bodies etc. I think only one I'm missing are has giants.

The other bit that needs a little attention is how to show whether they've been discovered / mapped before (aside from their value)..

**Comment by joncage** [comment]
A more complete example:

![image](https://user-images.githubusercontent.com/73681/91361277-df6ec500-e7ef-11ea-8c5e-2c7d622483f8.png)
