### ISSUE TITLE
AV Detects as Trojan

### ISSUE THREAD

**Issue by november781** [joncage/ed-scout#150]
This just started recently that Sophos will detect the exe file as Troj/AutoG-KP and will remove the file. I am still looking into why this is.

https://www.virustotal.com/gui/file/cd63e536fe177452883eca53322bba3bb79334f3ab85a16acc6846544da2c207/detection

**Comment by november781** [comment]
Updating with a list of AVs that are detecting this file as malicious
![image](https://user-images.githubusercontent.com/28309327/102439361-288b9480-3fec-11eb-91b9-2538383118b2.png)

**Comment by november781** [comment]
Probably my last update, this time with the rules that have likely triggered the detection 
![image](https://user-images.githubusercontent.com/28309327/102440604-8b7e2b00-3fee-11eb-99f2-2dca9c46e3c3.png)

**Comment by rocknrollbetty** [comment]
Same problem here - with norton AV.  I overrode norton, then tried to re-install, but edscout said previous install was incomplete and wanted to do a system restart.....so i declined and un-installed. Not confident it is safe.

**Comment by joncage** [comment]
The software is open source so you're welcome to make your own judgement. I package it up on my development machine and publish it here but if you look at the above listings, those are inline with the content of the software and are IMO innocuous.

For most releases, various virus checkers have flagged it. Microsoft have always reverted that (I suspect automated) initial decision.

You should always do what you feel best of course, but to the best of my knowledge there is nothing nasty lurking in EDScout.

**Comment by november781** [comment]
> The software is open source so you're welcome to make your own judgement. I package it up on my development machine and publish it here but if you look at the above listings, those are inline with the content of the software and are IMO innocuous.
> 
> For most releases, various virus checkers have flagged it. Microsoft have always reverted that (I suspect automated) initial decision.
> 
> You should always do what you feel best of course, but to the best of my knowledge there is nothing nasty lurking in EDScout.

I'm sure it's mostly safe, did a bit of digging for the earlier comments, but just be worth looking for an alternative to pyinstaller which is what is triggering these as far as I can tell.

**Comment by rocknrollbetty** [comment]
thanks for the response ... 'fraid code trawling is a bit beyond me now - IBM mainframe girl here! <showing her age :)> maybe I'll just have another try!

**Comment by joncage** [comment]
Haven't heard any reports of 1.8.2 doing this so closing for now.
