### ISSUE TITLE
ed scout shows only some data

### ISSUE THREAD

**Issue by doomster** [joncage/ed-scout#158]
when on a system, it works correctly. Shows data of current system, and next system, but does not show up all other systems in my route.
![image](https://user-images.githubusercontent.com/8209904/106134671-8aa0f300-616f-11eb-875a-fd6cdf29a008.png)

![image](https://user-images.githubusercontent.com/8209904/106134709-98ef0f00-616f-11eb-8be7-f267a052bfa9.png)

i am also using EDMC to upload data to inara/edsm dunno if it conflicts somewhere.

**Comment by Kepas-Beleglorn** [comment]
Could be related to this issue. #156
