### ISSUE TITLE
Add Option to Set App Background Color

### ISSUE THREAD

**Issue by rabbibob** [joncage/ed-scout#164]
Would you consider a local override for the background color of the display?  I was hoping to permanently set the background of the display to OBS's "green" for the Chroma Key filter to allow EDScout to be run as transparent while streaming.  I did see some test_.xml file references in the python code and that made me curious, or perhaps a setting in the appdata config file.

I'd additionally be happy if I could get the EDScout name in the title bar more visible in the OBS Source layer, but I think that's a different thing entirely.

No worries if not, I can edit local css for the effect as well (see example: [https://youtu.be/geVzURgB9y8](https://youtu.be/geVzURgB9y8) )

This may be in the same area as #60 and #68 for Enhancements.

Thank you!

**Comment by joncage** [comment]
Yep. Should be feasible to do this - just needs a config option plumbing in.
