### ISSUE TITLE
Lastest update seems broken - won't display data at all

### ISSUE THREAD

**Issue by packet1** [joncage/ed-scout#169]
I'm running with the CLI web server option and I don't see any data on the local GUI or the webserver

![image](https://user-images.githubusercontent.com/70610088/109372395-e776f280-786e-11eb-9272-637714a01a5c.png)

**Comment by joncage** [comment]
Looks like a bug alright. I'll take a look at that later today / tonight. Apologies!

**Comment by miksmax** [comment]
Nothing displaying for me either. Only thing I can provide is the text from the debug.log:
[0124/212901.604:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)

**Comment by packet1** [comment]
[EDScout-2021-02-27-00-56-52.log](https://github.com/joncage/ed-scout/files/6054636/EDScout-2021-02-27-00-56-52.log)
[EDScout-2021-02-27-00-53-39.log](https://github.com/joncage/ed-scout/files/6054637/EDScout-2021-02-27-00-53-39.log)
[EDScout-2021-02-27-00-49-55.log](https://github.com/joncage/ed-scout/files/6054638/EDScout-2021-02-27-00-49-55.log)
[EDScout-2021-02-27-00-49-02.log](https://github.com/joncage/ed-scout/files/6054639/EDScout-2021-02-27-00-49-02.log)
[EDScout-2021-02-27-00-48-00.log](https://github.com/joncage/ed-scout/files/6054640/EDScout-2021-02-27-00-48-00.log)
[EDScout-2021-02-27-02-14-01.log](https://github.com/joncage/ed-scout/files/6054641/EDScout-2021-02-27-02-14-01.log)
[EDScout-2021-02-27-02-09-40.log](https://github.com/joncage/ed-scout/files/6054642/EDScout-2021-02-27-02-09-40.log)
[EDScout-2021-02-27-02-05-53.log](https://github.com/joncage/ed-scout/files/6054643/EDScout-2021-02-27-02-05-53.log)
[EDScout-2021-02-27-02-02-32.log](https://github.com/joncage/ed-scout/files/6054644/EDScout-2021-02-27-02-02-32.log)
[EDScout-2021-02-27-01-37-43.log](https://github.com/joncage/ed-scout/files/6054645/EDScout-2021-02-27-01-37-43.log)
[EDScout-2021-02-27-01-31-19.log](https://github.com/joncage/ed-scout/files/6054646/EDScout-2021-02-27-01-31-19.log)
[EDScout-2021-02-27-01-01-41.log](https://github.com/joncage/ed-scout/files/6054647/EDScout-2021-02-27-01-01-41.log)
[EDScout-2021-02-27-00-58-05.log](https://github.com/joncage/ed-scout/files/6054648/EDScout-2021-02-27-00-58-05.log)

Here  are my journals from last night

**Comment by packet1** [comment]
![image](https://user-images.githubusercontent.com/70610088/109390845-9223fb00-78d9-11eb-96c0-1d88123573e8.png)

**Comment by packet1** [comment]
Why do I see a request against port 5001?  I run EDscout on port 333.

![image](https://user-images.githubusercontent.com/70610088/109393127-b554a780-78e5-11eb-8cb2-1c41cda2495c.png)

**Comment by packet1** [comment]
[EDScout-2021-02-27-15-53-24.log](https://github.com/joncage/ed-scout/files/6055224/EDScout-2021-02-27-15-53-24.log)

**Comment by joncage** [comment]
> Why do I see a request against port 5001? I run EDscout on port 333.

5001 is a keepalive channel which is suppoed to ensure that if the web front end is closed, that the backend also closes down.

**Comment by packet1** [comment]
I see.  LMK if you need any more logs, etc.

**Comment by joncage** [comment]
Found the problem - stupid oversight on my part (should have tested with some unmapped systems!). Will be fixed in 1.8.1

**Comment by packet1** [comment]
Thanks, Jon!
