### ISSUE TITLE
What does it mean if not all bodies in my nav panel show up on EDScout? 

### ISSUE THREAD

**Issue by Dthen** [joncage/ed-scout#175]
What determines which it shows and leaves out?
![image](https://user-images.githubusercontent.com/65791582/111044161-abcb5380-843e-11eb-9a3b-aa72bd85ad4e.png)
![image](https://user-images.githubusercontent.com/65791582/111044167-bb4a9c80-843e-11eb-907a-095b3248422b.png)
https://eddb.io/system/90

**Comment by joncage** [comment]
By design. in an already-discovered system, it just highlights the valuable ones (anything over 500k).
