### ISSUE TITLE
EDScout Installer won't go beyond the Windows unsigned code verification

### ISSUE THREAD

**Issue by eplossl** [joncage/ed-scout#204]
So I have tried to install several times this afternoon so that I could try this out.  Each time I start the installer, it starts to start, causes Windows to complain about it being unsigned code and ask if I really wanted to do this, and when I said yes it then does nothing that I can see. It does not appear to install anything and doesn't proceed any further. I looked through the Windows Event Viewer to see if I could find any installer logs, to no avail. If you can tell me where logs of the install get placed, I can see what I can come up with for you in terms of additional data about the install.  

For what it's worth, I'm running Windows 10 Home edition version 21H1.

**Comment by SigmaCeti** [comment]
I've the same problem

**Comment by eplossl** [comment]
For what it's worth, I tried running it this afternoon as Administrator on my windows machine and it still didn't do anything that I can see.
