### ISSUE TITLE
Trojan:Win32/Zpevdo.B

### ISSUE THREAD

**Issue by EDChurly** [joncage/ed-scout#43]
![image](https://user-images.githubusercontent.com/15647838/91112070-43df3680-e6c1-11ea-864a-b8789df861d0.png)

Windows defender is reporting as attached in version EDscout v1.2.3

**Comment by lulunzb** [comment]
Just updated to v1.2.5 and didn't get any threats.  I suspect is just a false positive.

**Comment by joncage** [comment]
Reported to MS here: https://www.microsoft.com/en-us/wdsi/submission/ff213a11-6db9-42a6-8661-02473ceff9ad

**Comment by joncage** [comment]
Microsoft confirm:

> Submission ID: ff213a11-6db9-42a6-8661-02473ceff9adStatus: 
> Submitted: Aug 25, 2020 09:42:58
> User Opinion: Incorrect detection
> 
> Analyst comments:
> 
> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
