### ISSUE TITLE
flaskwebgui error

### ISSUE THREAD

**Issue by Rhaedas** [joncage/ed-scout#54]
Tried 1.3 to take a look, got hung on waiting for a plot in the GUI. Loaded the log, it's not finding something.

[EDScout-2020-08-28-16-25-18.log](https://github.com/joncage/ed-scout/files/5143191/EDScout-2020-08-28-16-25-18.log)

I just replaced 1.2.5 (which was working) with this exe.

**Comment by joncage** [comment]
Looks like the chrome web browser isn't being detected on your system.

**Comment by joncage** [comment]
If the GUI appears but nothing happens when you plot a route, it's possible something is falling over in the GUI. You could try double checking whether...

* if you connect a browser.to 127.0.0.1:5000 does developer more show up any issues?
* If you check the directory with notepad etc does that cause it to spring into life? Maybe I broke the bit that was prompting updates to the journals from being passed on...

**Comment by Rhaedas** [comment]
Definitely weird. Messing with the directory didn't affect anything, so I backtracked to previous versions that worked, and now had similar issues (no flaskwebgui error in the log, but not loading like before). Then they finally started working. I finally tried 1.3, clicked on the journal file like before, and it loaded the route. Still has the error in the log.

[EDScout-2020-08-28-23-17-41.log](https://github.com/joncage/ed-scout/files/5144455/EDScout-2020-08-28-23-17-41.log)

That 1.2.5 and 1.2.4 were working and now aren't suggests something changed here, although I haven't done anything different.

Going to do more comparisons between versions, see if I can narrow down what's going on. Chrome update maybe? Shouldn't break things like that.

**Comment by joncage** [comment]
Lots to pick apart there. Sounds like something odd is going on behind the scences.

> I do notice that after trying a few times with no success and then when it works, it would read all the routes in until it got to the latest one.

If something was preventing it from loading routes, I'd expect it to just load the last one (although it might load that route multiple times if it was scanning through a lot of navroute journal entries.

#33 should deal with a cleaner / more sensible startup. If there are multiple nav route calls, the latest scout should spot that it's reloading an unchanges navroute file and avoid re-plotting if nothing changed (i.e. start and end are identical).

This log message shows at one point it was ~30s out for some reason:

```
2020-08-28T23:20:53.352Z - EDScoutCore-EDScout - INFO - Reporting: {"timestamp": "2020-08-28T23:20:33Z", "event": "Cargo", "Vessel": "Ship", "Count": 0, "Inventory": [], "type": "JournalEntry"}
```

Note the timestamp diferences. The first is the scout and the second is the game.

I think the chrome messages were a red-herring. Next release should turn them off.

**Comment by joncage** [comment]
Re-running with `EdScout.exe -log_level 10` might give us a bit more to go on (enables debug logging).

**Comment by joncage** [comment]
I managed to get my system in  a similar sounding state. only way i recovered it was to close chrome then close all the hidden chrome instances from task manager. Need to find a way to identify these background chrome processes so they can be culled safely.

**Comment by Rhaedas** [comment]
I believe you can close this, as 1.4 works perfect for me.

**Comment by joncage** [comment]
Still, I had a cunning idea when I woke up this morning. We know the paid when we launch chrome I believe so we could write that value to a file each time we launch one. That way we can recall current chrome launches and kill those off too. Simple and should be effective.

**Comment by joncage** [comment]
Will handle this in #71
