### ISSUE TITLE
More cosmetic suggestions

### ISSUE THREAD

**Issue by Rhaedas** [joncage/ed-scout#58]
A way to set font sizes, maybe even fonts, and adjust the column widths. Just to further help the user blend it in with the rest of the HUD. Also some internal way to set the window to stay on top and/or have a hot key to bring it to the front while playing. Right now I'm using another program "WindowTop" to do that for me, but for single monitor players a hotkey would be useful. I suppose anyone using Voice Attack could make a command for that, but not everyone runs that.

**Comment by joncage** [comment]
I right in thinking you have to play in non-fullscreen mode to be able to switch windows like that?

Column widths are tricky because it's using bootstrap to do the layout so they're supposed to flex as you resize the screen.

Hotkey might well be doable. 

Could expose the .CSS data that sets fonts etc. - out of interest, why the request? I tried to used the same font /size as the game.

**Comment by Rhaedas** [comment]
Yes, I think it only works with borderless windows.


![Unknown 08-30-20 13·10·05](https://user-images.githubusercontent.com/69368125/91665511-209ef780-eac4-11ea-9fc8-579af438c8c1.png)

Here's a screenshot of what I have (across three screens). You can see with the extra info I have to stretch the window out more, covering more of the left view. I have the ability to make it more transparent, so I can still see through it, but if I could reduce the font some and/or set columns I could compress it more to the left out of the way.

It's not a huge problem. Another solution I just thought of for my personal use, I could have Voice Attack expand and contract the window size depending on my needs, so that's another option (and might go well with the rest of the HUD popup info.

**Comment by joncage** [comment]
Gotcha. I can make the name box wider for systems and leave it the same when scanning via RSS would make a difference here.

I'm thinking about ditching the titles again too - thoughts?

**Comment by joncage** [comment]
Implemented toggling (on START+Z) - will be part of the next release.

**Comment by joncage** [comment]
Give this a shot: [EDScout-v1.4.0-4-g46dad88.zip](https://github.com/joncage/ed-scout/files/5147628/EDScout-v1.4.0-4-g46dad88.zip)

I've made the star type appear in `[]` before the system name and merged that right:

![image](https://user-images.githubusercontent.com/73681/91671473-e6af0f00-eb1e-11ea-8b11-8b29dafa1789.png)
