### ISSUE TITLE
Trojan warning (Wacatac.C!ml) for EDScout.exe 1.4.0

### ISSUE THREAD

**Issue by raycelander** [joncage/ed-scout#59]
Windows Defender detects the trojan Wacatac.C!ml in EDScout.exe 1.4.0.
The Windows Defender's security pattern is from 30.08.2020

**Comment by joncage** [comment]
That's the second time a version of the scout has been picked up. I think I need to automate that check and the process of submitting it to Microsoft. Cheers for the heads up. I'll pass that on to them...

**Comment by joncage** [comment]
Reported to Microsoft here: https://www.microsoft.com/en-us/wdsi/submission/d25b97e8-5bca-4974-b07c-fb47851294e9

**Comment by joncage** [comment]
MS Say:

> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
