### ISSUE TITLE
List does not stay on top when entering a new system or scanning bodies

### ISSUE THREAD

**Issue by raycelander** [joncage/ed-scout#67]
Currently the list scrolls down when new items get appended.
The current star system should kept visible.

**Comment by joncage** [comment]
Fair point. Maybe it would make sense to add new items at the top and scroll the rest down / out of view then?

**Comment by raycelander** [comment]
I would revert the behaviour to the previous version 1.3.0, because it was ok there. And if you reduce the font size, enough information would be visible.

**Comment by joncage** [comment]
If you don't scroll them down then for busy systems, you lose the new stuff off the bottom of the list. That's why I altered it to scroll to the latest item in 1.4

Font size will only get you so far.

**Comment by raycelander** [comment]
> If we put new stuff at the top and scroll it down, keeping any valuable systems at the very top I reckon that's a good balance.

I guess I'd be happy with this solution.
 
> Could make the overall font size a configurable option though for extra customisation.

An option for adjusting the font size and weight would be nice!

**Comment by joncage** [comment]
> An option for adjusting the font size and weight would be nice!

Out of interest, this is so that you can fit more lines of information into the screen right? If you have any screen shots of the way you use the scout, that always helps me get a feel for things when I'm making adjustments like this.

**Comment by raycelander** [comment]
Yes. I'd like to see more information on the screen. That's one thing. Another thing is, smaller fonts make it more readable and more comfortable for the eyes. At least for me. It depends on the screen's resolution, of course.

I'm using EDScout on my second screen with a resolution of 1920x1080:
![edscout_scrn](https://user-images.githubusercontent.com/12814766/91728960-210ebf80-eba4-11ea-84fc-be20709e8dc5.png)

If I could reduce the font size, I would set it to 14px to have much more content visible:
![edscout_scrn_font_14px](https://user-images.githubusercontent.com/12814766/91728714-c70dfa00-eba3-11ea-856c-04a7181d8e8b.png)

**Comment by joncage** [comment]
Just a thought (I've not tried this and don't have my Dev machine handy) but if you have the scout active and use CTRL and the scroll wheel, does that work as far as altering font size?

**Comment by raycelander** [comment]
Well. Silly me! Of course this works!

**Comment by joncage** [comment]
Cool! Still might find a way to make that a more permanent option longer term but good to have a short-term workaround for it too 👌🏻

**Comment by raycelander** [comment]
The zoom level is restored when EDScout is opened again.
Therefore, no further action is required on this issue.

**Comment by joncage** [comment]
Good to know but I'm still changing it to put newest discoveries at the top and pin valuable systems to the top of the list :)
