### ISSUE TITLE
1.4 seems completely broken

### ISSUE THREAD

**Issue by packet1** [joncage/ed-scout#74]
The current location and nav route are not updating at all.  

The web server isn't providing any data at all. 

This all worked in version 1.3.

**Update**
For unknown reasons, after a restart of the app, it is now updating with data and the web server is working.

**Comment by joncage** [comment]
Weird. Keep an eye on it and if you spot any patterns that lead to this, update this report. I'll keep it open for now.

**Comment by joncage** [comment]
Heard no more so I'm closing this for now.
