### ISSUE TITLE
enhancement - update within the app

### ISSUE THREAD

**Issue by packet1** [joncage/ed-scout#75]
Like the EDMC or EDDN, provide a facility to update the app from within the app.

**Comment by joncage** [comment]
Yep, good idea this one.

**Comment by joncage** [comment]
Looks like edmc uses winsparkle to do the update.. https://github.com/EDCD/EDMarketConnector/blob/main/update.py

**Comment by joncage** [comment]
Going to add a version check that highlights new versions with a link that takes you to the latest page on github as a starter.
