### ISSUE TITLE
When a body is mapped, drop it down the list

### ISSUE THREAD

**Issue by joncage** [joncage/ed-scout#79]

**Comment by gqgunhed** [comment]
Either drop it down the list or change the color of the "mappable" flag to green.

**Comment by joncage** [comment]
Good call. Maybe switch it to a green tick (and drop it down the list)?

**Comment by joncage** [comment]
Should just be a case of checking for events like this and looking up the body ID:

```
{ "timestamp":"2020-09-28T21:19:03Z", "event":"SAAScanComplete", "BodyName":"Wredguia GH-D d12-6 3", "SystemAddress":216501602667, "BodyID":4, "ProbesUsed":5, "EfficiencyTarget":6 }
```

If we find a match:

1) set the unmapped flag colour like the landable style (colour-wise)
2) change it's style to that of a discovered body
3) move it to the top of the less valuable list.

**Comment by joncage** [comment]
I have the bulk of this fixed I think but which looks better?

![image](https://user-images.githubusercontent.com/73681/94615619-f5185400-029f-11eb-93c5-cffd76496e15.png)

![image](https://user-images.githubusercontent.com/73681/94615805-432d5780-02a0-11eb-9200-3f109fe5130a.png)

I think the latter is more consistent i.e. clearing the unmapped flag.
