### ISSUE TITLE
Windows Defender reports trojan warning for EDScout 1.5.1. 

### ISSUE THREAD

**Issue by raycelander** [joncage/ed-scout#84]
Hi Jon

Windows Defender has again started to report a Trojan warning for EDScout 1.5.1.
You really should remove those viruses! ;-)

**Comment by joncage** [comment]
What Trojan warning do you get (so I can make another submission).

Honestly, how many times Microsoft?!

**Comment by raycelander** [comment]
Sorry for being unspecific.
Now it's for Trojan:Win32/Wacatac.D6!ml

**Comment by joncage** [comment]
Thanks! I've re-submitted it.

**Comment by joncage** [comment]
Submitted here: https://protect-eu.mimecast.com/s/Ui4dC6XXxhPP27XU6LtZe?domain=microsoft.com

**Comment by joncage** [comment]
Microsoft confirm..

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.
