### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by JhonDow0175** [joncage/ed-scout#91]
Windows defender marks EDScout.exe as "Win32/DefenseEvasion.WI!ml"

**Comment by joncage** [comment]
Urgh - they do this with every single release after a few days it seems! Thanks for the heads up. I will report it to Microsoft and report back here when they've unblocked it...

**Comment by joncage** [comment]
Did the installer do the same thing or just the standalone exe?

**Comment by joncage** [comment]
Submitted the stand-alone .exe here: https://www.microsoft.com/en-us/wdsi/submission/7ce0f295-a1c9-4c50-8c68-fd8d8e796dd6

**Comment by joncage** [comment]
Microsoft confirm:

```
We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
```
