### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by artig4n** [joncage/ed-scout#93]
This is a pretty cool idea. I like how it categorizes the bodies as you scan them. That part is useful because it ensures that you don't miss anything.

But, it skips a couple of important things. 

1) I'd like to be informed if the body has geological or biological features (or any locations, really).
2) I'd like to be informed if the body has rings, and what kind they are

The navigation path part is useless to me, because I'm out exploring in the black where nothing is discovered. So all I get is a list of question marks.

Also, the navigation path doesn't work if you're travelling by carrier.

So I'd like to just disable that part, it takes up a lot of space for no reason out here.

Lastly, I had to use OnTopReplica to put your window over the ED window. It works well enough, but other similar tools for ED just use a window that can be set to always on top. That would be preferred.

Anyway, I think you're onto something here. Keep it up!

**Comment by joncage** [comment]
Geological comes from volcanism + landable but I've yet to determine how to spot biological signals from the log files elite produces (it's on my to-do list to review the biological systems I've seen in case there's something that identifies them l). It would duplicate the information a bit but I've thought about adding an extra icon for geological a few times.

Showing rings is certainly doable. How do you picture the type being shown?

Turning off the nav path would be very easy.

As far as being on top or not, have you tried hitting `START`+`Z`? It should show / hide the window behind the game. This only works in windowed / borderless lode though it think.

I don't have a carrier but if, while using one, you never visit the galaxy map and plot a route then that would make sense. I don't think there's much I can do about that. Will have to save up and find out 😉

**Comment by artig4n** [comment]
Sounds good. 

Right now I still have to scan through the System map after I do an FSS to check for biologicals and whatnot. Also check for locations such as ruins. So it would be nice to have those things auto-highlighted by EDScout. 

As for how to show the ring type, just a couple letters would do it (R for rocky, I for Icy, MR for Metal Rich, ME for Metallic, something like that?)

I don't know what you mean by START+Z, though. I don't have a START button on my keyboard.

On the carrier, you do use the Galaxy map to plot your jump, but it's just one jump.

**Comment by joncage** [comment]
Start = the windows key.

I'll knock up some prototypes for display rings so we can have a think about how best to display that...

**Comment by joncage** [comment]
Where can I find some ruins to check against? ..or do you have any journal files which show where you discovered some I could peek at to see if I can detect them?

**Comment by joncage** [comment]
I've pulled all the requests in this discussion into separate targetted feature requests so I'm going to close this discussion.
