### ISSUE TITLE
Show ring information.

### ISSUE THREAD

**Issue by joncage** [joncage/ed-scout#96]
As per discussion in #93 from @artig4n:

> I'd like to be informed if the body has rings, and what kind they are. Just a couple letters would do it (R for rocky, I for Icy, MR for Metal Rich, ME for Metallic, something like that?)

**Comment by joncage** [comment]
How about something along these lines @artig4n ?

![image](https://user-images.githubusercontent.com/73681/94743987-2ceecc80-0370-11eb-8854-98821a091527.png)

**Comment by artig4n** [comment]
That would work :)

**Comment by joncage** [comment]
Ah, didn't know that was a thing but yes, something like that could work I think. Need to trawl back through my journals for some examples and see how silly it gets - what do you think the max number of rings is?

**Comment by artig4n** [comment]
Hmm. I've never seen more than 3, but there may be some.

**Comment by joncage** [comment]
Wrote a quick Python script which told me:

```
Max rings: 3
Types: {'MetalRich', 'Rocky', 'Icy', 'Metalic'}
```

Any reason to distinguish between `MetalRich` and `Metalic` rings as far as the icons go?

**Comment by joncage** [comment]
Okay, a bit crude but here's my first stab (this is picking up the info from the scan...

![image](https://user-images.githubusercontent.com/73681/94867894-ff6e5580-0439-11eb-9414-07163aff3e96.png)

**Comment by artig4n** [comment]
Looks pretty cool! 

As far as Metallic vs Metal Rich, yes, they are quite different. Metallic is good for laser mining Painite, whereas Metal Rich is not. Metal Rich is only good for Core mining. 

So both types should be distinguished, I think.

**Comment by joncage** [comment]
Would three metal bars vs one metal bar for metal-rich vs metallic do it for you?

**Comment by artig4n** [comment]
Sure, that works.

**Comment by joncage** [comment]
Tried an experiment tonight:

![image](https://user-images.githubusercontent.com/73681/95002909-15624e80-05d1-11eb-8487-92246788af4f.png)

...but I actually think the version above with the more basic brackets looks clearer so will probably go back to something more like that.

**Comment by artig4n** [comment]
Either one works for me. What are the brackets for, just separators?

**Comment by joncage** [comment]
Yup. Just to give a visual cue that they're rings around the body.

**Comment by joncage** [comment]
Final version that will be in the next release:

![image](https://user-images.githubusercontent.com/73681/95027303-5caf1480-068f-11eb-9134-df553c9c2577.png)

**Comment by artig4n** [comment]
Cool beans. I'll definitely test it out!
