### ISSUE TITLE
Hard to tell already mapped bodies

### ISSUE THREAD

**Issue by lunemec** [joncage/ed-scout#99]
When you have system with multiple worth-to-scan bodies, it is hard to tell using edscout which you already mapped and which still remain. EDD shows little green globe to indicate this. I think something similar, or just changing the color to green and moving the body lower would be very nice.

**Comment by joncage** [comment]
Agreed although I think this duplicates the suggestion in #79 😉

**Comment by joncage** [comment]
Closing this as it'll be tackled under #79 - I made a start on it last night.
